
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/kinetic64"
    # copiar la app de host a guest
    config.vm.provision :file, source: './app', destination: "$HOME/app"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end