name: Releases

on: create

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Dockerfile"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}